### ISSUE TITLE
Investigate auth problem with chapter 12

### ISSUE THREAD

**Issue by briandoconnor** [broadinstitute/genomics-in-the-cloud#114]
When I tried running the following:

```python
# Load the variant track
IGV_Explore.load_track(
    {
        "name": "Workspace bucket copy of Mother WGS",
        "url": WS_BUCKET + "sandbox/mother.bam",
        "indexURL": WS_BUCKET + "sandbox/mother.bai",
        "format": "bam",
        "oauthToken": token
    })
```

I got the following error:

![image](https://user-images.githubusercontent.com/1730584/72770486-dad79380-3bb2-11ea-8ac8-7c738fc31bde.png)

I think there's an auth step not described in the chapter that needs to be run before this track can be loaded

**Comment by vdauwera** [comment]
bad paths, facepalm
