### ISSUE TITLE
Brian's QC2 read-through

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/genomics-in-the-cloud#124]
## About

Shared draft + revised figures + workspace + notebook

A ticket for me to track when I've read through the latest version of each chapter

## Comment Check

* [x] Praise, front matter,  and foreword
* [x] Preface 
* [x] Chapter 1 
* [x] Chapter 2
* [x] Chapter 3 
* [x] Chapter 4 
* [x] Chapter 5
* [x] Chapter 6
* [x] Chapter 7
* [x] Chapter 8 
* [x] Chapter 9 
* [x] Chapter 10
* [x] Chapter 11
* [x] Chapter 12 
* [x] Chapter 13 
* [x] Chapter 14 

## Tech Check

* [x] Praise, front matter,  and foreword
* [x] Preface
  * only issue is do we use the shortened URL for the GitHub page?  I think no personally.
  * on page XX we say "Constant width bold" are commands that should be typed literally by the user.  But we don't ever actually use that throughout the book!
* [x] Chapter 1 
* [x] Chapter 2
* [x] Chapter 3 
* [x] Chapter 4 
  * major issue that's easy to fix, we have a copy of the code in the google bucket and that needs to be removed, see https://github.com/broadinstitute/genomics-in-the-cloud/issues/125
* [x] Chapter 5
  * I ran into problems with IGV 2.6.2 for auth to access my own VCFs in my own bucket.  See https://github.com/broadinstitute/genomics-in-the-cloud/issues/126  2.7.2 works fine for me.  We may need to update the version of IGV we recommend in the book
* [x] Chapter 6
* [x] Chapter 7
* [x] Chapter 8 
* [x] Chapter 9 
* [x] Chapter 10
* [x] Chapter 11
* [x] Chapter 12 
  * workspace needs to be finalized: https://app.terra.bio/#workspaces/fccredits-rhenium-olivine-6354/Genomics%20in%20the%20Cloud%20v1%20-DEV-%20copy%20copy/notebooks/launch/Genomics%20Notebook.ipynb
  * the notebooks need to be cleaned up
* [x] Chapter 13: rushed
* [x] Chapter 14: rushed

## Tech Second Pass

* [ ] Chapter 13
* [ ] Chapter 14
* [ ] extract http URLs and check they are valid

**Comment by briandoconnor** [comment]
## Figure Problems

* 2-10 in grayscale is impossible to tell the difference between reference and alt allele
*

**Comment by briandoconnor** [comment]
## Env Vars

```
export BUCKET="gs://genomics-in-the-cloud-boconnor"
export BIN=~/book/bin
export WF=~/book/code/workflows
export CASE1=~/book/code/workflows/mystery-1
export CASE2=~/book/code/workflows/mystery-2
```

**Comment by briandoconnor** [comment]
Template


* [ ] Praise, front matter,  and foreword
* [ ] Preface 
* [ ] Chapter 1 
* [ ] Chapter 2
* [ ] Chapter 3 
* [ ] Chapter 4 
* [ ] Chapter 5
* [ ] Chapter 6
* [ ] Chapter 7
* [ ] Chapter 8 
* [ ] Chapter 9 
* [ ] Chapter 10
* [ ] Chapter 11
* [ ] Chapter 12 
* [ ] Chapter 13 
* [ ] Chapter 14
