### ISSUE TITLE
Remove 'code' directory from cloud storage

### ISSUE THREAD

**Issue by briandoconnor** [broadinstitute/genomics-in-the-cloud#125]
Code checkout on page 105 is broken since there is already a code directory in the google bucket:

boconnor@genomics-book:~/book$ ls
bin  code  data  wdl_runner
boconnor@genomics-book:~/book$ ls code/
LICENSE  README.md  _config.yml  commands  config  metadata  notebooks  pygments_lexer  temp  workflows
boconnor@genomics-book:~/book$ git clone https://github.com/broadinstitute/genomics-in-the-cloud.git code
fatal: destination path 'code' already exists and is not an empty directory.

We need to remove the code directory from the google bucket (or rename it).

**Comment by vdauwera** [comment]
Removed the code dir from bucket, replaced with scripts/ directory for the two scripts we need to have on cloud (for notebooks)
