### ISSUE TITLE
Finalize example notebook for Ch 12 

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/genomics-in-the-cloud#89]
All text content development is done but I still need to put together the final version of the notebook. That in turn is needed for finalizing code cells and screenshots.

**Comment by briandoconnor** [comment]
As a heads up, Chapter 13 (page 387) points to the notebook file and other code in the bucket.  I think we need to point those at GitHub.  The notebook dir on github is currently empty:

https://github.com/broadinstitute/genomics-in-the-cloud/tree/master/notebooks

**Comment by vdauwera** [comment]
There are two scripts that we provide via the bucket intentionally (makes it easier to retrieve them). For the notebook file I should have pointed to GitHub — can you record the specific place where the text points to the bucket? 

I’m still working on finalizing the notebook, will check in a copy when it’s done.

**Comment by briandoconnor** [comment]
Also, FYI, we have a note on page 349 that says:

"From this point on, we don’t show the output of the cells. You can check your outputs against the copy of the
notebook included in the Terra workspace. We also provide an html version of the pre-run notebook in the
book’s Github repository."

I think this is satisfied by the notebook rendering feature of GitHub but I just wanted to point tis out.

**Comment by briandoconnor** [comment]
Responding to @vdauwera , on page 387 we have an o'reilly redirect that points to: https://console.cloud.google.com/storage/browser/genomics-in-the-cloud/book-bundle-v0/code/notebooks

I made a comment in my PDF (that I'm about to send off) that suggests we switch this to https://github.com/broadinstitute/genomics-in-the-cloud/tree/master/notebooks

**Comment by vdauwera** [comment]
Oh yeah that should definitely point to GitHub — great point about the link shortened, presumably we can get those pointed correctly easily.
